### ISSUE TITLE
Implement AveragePool and Pad operators in simplego backend

### ISSUE THREAD

**Issue by recursionerr** [gomlx/gomlx#243]
It would be nice to have these two operators in the default backend:

https://onnx.ai/onnx/operators/onnx__AveragePool.html
https://onnx.ai/onnx/operators/onnx__Pad.html

Ref https://github.com/knights-analytics/hugot/issues/92

Unfortunately I don't have a good enough understanding of ML operations and gomlx to implement them myself.

**Comment by janpfeifer** [comment]
Those should be easy, there are corresponding GoMLX operators:

- https://pkg.go.dev/github.com/gomlx/gomlx@v0.23.2/graph#MeanPool
- https://pkg.go.dev/github.com/gomlx/gomlx@v0.23.2/graph#Pad

Let me see if I can do them in the next couple of days, I'll keep you posted.

**Comment by janpfeifer** [comment]
I (with some AI help) took a first stab at it. I just merged to `main` if you want to give it a try.

I didn't convert all options -- there are optional parameters in the ONNX ops that would be harder to implement, so I simply return an error if they are used. Let me know if you bump into one of those, we can  add them as needed.

**Comment by recursionerr** [comment]
It doesn't seem like those ops are there in the main branch. Maybe a git push is needed? 😄

**Comment by janpfeifer** [comment]
I'm sorry, maybe you are not aware, but the ONNX to GoMLX conversion is a separate repo, in [https://github.com/gomlx/onnx-gomlx/](https://github.com/gomlx/onnx-gomlx/), the change was merged in [PR#30](https://github.com/gomlx/onnx-gomlx/pull/30)

**Comment by recursionerr** [comment]
Got it, so I updated to the latest (v0.3.1) release of onnx-gomlx, and all the models load fine. But the simplego backend still doesn't have an actual implementation of these operations.

I still get:
```
failed to run forward pass: sorry, op "Pad" not implemented in SimpleGo yet -- reach out to github.com/gomlx/gomlx and open an issue if you need this op, this helps us prioritize the work: not implemented
```
